{% set name = "mcreweight" %}
{% set version = "0.3.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mcreweight-{{ version }}.tar.gz
  sha256: 409042f2ddbbd292ffd85f5f88b7c90c0db36a07e144d04820de121ad7ec89ea

build:
  entry_points:
    - run-reweight = scripts.run_reweighting:main
    - apply-weights = scripts.apply_weights:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.20.0
    - pandas >=1.3.0
    - matplotlib-base >=3.4.0
    - scikit-learn >=1.0.0
    - optuna >=2.10.0
    - hep_ml >=0.7.0
    - seaborn >=0.11.0
    - awkward-pandas >=2023.8.0
    - numexpr >=2.7.0
    - uproot >=5.0.0,!=5.6.8
    - awkward >=2.6.0

test:
  imports:
    - mult_and_kin_reweight
    - scripts
    - utils
  commands:
    - pip check
    - run-reweight --help
    - apply-weights --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/tfulghes/mcreweight
  summary: Tools for reweighting Monte Carlo samples to match experimental data distributions
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tfulghes7
